server:
  port: 5432


spring:
  profiles:
    active: dev

---

spring:
  datasource:

    password: 4f8b8c40df43183a84956a17141ee971201211ed3495a131e557423ac571da93
    url: jdbc:postgresql://ec2-52-209-171-51.eu-west-1.compute.amazonaws.com:5432/d762umm80qs4kj
    username: kqnfefngoqdgbd
  
  config:
    activate:
      on-profile: dev


---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: sanzar
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: qa
welcome:
  message: Welcome to Daily Code Buffer!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!