server:
  port: ${PORT:5432}


spring:
  profiles:
    active: dev

---

spring:
  datasource:

    password: d5bca8560e11bc3c06c2b1fb851887b8c552d82f65ce14065f726428038636e7
    url: jdbc:postgresql://ec2-3-233-55-123.compute-1.amazonaws.com:5432/d8and89v4smfea
    username: tahkqmxjcsmjqj
  
  config:
    activate:
      on-profile: dev


---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: sanzar
    url: jdbc:mysql://localhost:3306/asaa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: qa
welcome:
  message: Welcome to Daily Code Buffer!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!